import { LitElement, html, nothing } from 'lit';
import '@material/web/all.js';
import '@fontsource-variable/inter';
import '@fontsource/noto-sans-hk/400.css';
import './style.css';

type Capability = { id:string; family:string; referenceCapability:string; equivalent:string; status:string; statusReason:string; intendedPage:string };
type Release = { version:string; state:string; downloadUrl:string|null; releaseUrl:string; updatedAt:string|null };
const source = 'https://github.com/Ding-Ding-Projects/material-system-care';
const sections = [
  ['01', 'Understand your computer', 'Live memory, storage, applications, startup records, drivers, and protection status. See the actual finding before deciding what to change.', 'Inventory'],
  ['02', 'Choose what changes', 'Review exact targets and effects. Confirm selected actions, keep sensitive operations separate, and see when administrator access is required.', 'Control'],
  ['03', 'Keep a way back', 'Temporary-file maintenance keeps recovery receipts. Conflicts and partial outcomes stay visible instead of disappearing behind a success badge.', 'Recovery'],
];
const docs: Record<string,{title:string; paragraphs:string[]}> = {
  start: {title:'Start with a scan, not a promise', paragraphs:['Material System Care targets Windows 11 x64. The desktop starts in a working maintenance workspace. Its records come from the local engine, and an unavailable measurement stays unavailable.','Open a workspace, inspect its records, and choose a contextual action. Analysis does not authorize changes. Every mutating workflow names its targets and requires confirmation.','The current release manifest controls the download button. Development source is available immediately, but an installer is offered only after its release link has been verified.']},
  safety: {title:'Clear changes. Honest recovery.', paragraphs:['Automatic maintenance is conservative and opt-in. It never performs blanket registry deletion, disables security protection, force-closes processes, or changes the computer’s power or login state.','Temporary-file cleanup uses server-issued plans. The engine rechecks the selected files before moving eligible items into recoverable storage. Restoration does not overwrite a newer file.','A recovery receipt is not a full computer backup. Some operations cannot be reversed automatically. Their workflow must disclose that limit before the user confirms.']},
  architecture: {title:'A native interface with a separate engine', paragraphs:['Flutter and Dart provide the Material Design 3 interface. C# and .NET 10 implement local operations and SQLite records. A small C++20 bridge connects the interface to the current-user local named pipe.','The interface remains unelevated. An operation that requires administrator rights reports that requirement explicitly. The initial scope uses supported user-mode APIs and excludes custom kernel drivers.','The public website uses TypeScript, Lit, and official Material Web components. Source, implementation coverage, and verification evidence remain separate records.']},
  privacy: {title:'Local work stays local', paragraphs:['Settings and operation records live in local application data. File tools process selected files locally unless the user deliberately enables a disclosed provider.','Provider features are opt-in. Credentials, private vocabulary files, file contents, and prompts do not belong in diagnostic logs, screenshots, exports, or published source.','Personal vocabulary is supplied only through a local JSON file. No private mappings ship with this website. Clearing the local setting restores the original wording.']},
  coverage: {title:'What coverage means', paragraphs:['The versioned catalogue maps reference capabilities to independently implemented equivalents. A listed capability is not automatically implemented.','Implemented, unverified, unavailable, excluded, and planned states are distinct. Provider access, hardware availability, operating-system support, and built evidence determine whether an operation is actually ready.','This project makes no inherited claim about vendor detection rates, performance improvements, guaranteed data recovery, or estimated frame rates.']},
};

/** Registered Material surface composition. Semantic document structure is internal. */
class MscSurface extends LitElement {
  createRenderRoot(){return this;}
  render(){return html`<section class="material-surface"><slot></slot></section>`;}
}
customElements.define('msc-surface', MscSurface);

/** Registered typography, navigation, article and workflow composition. */
class MscSite extends LitElement {
  static properties = {page:{state:true}, query:{state:true}, status:{state:true}, entries:{state:true}, release:{state:true}, theme:{state:true}, reduced:{state:true}, settingsOpen:{state:true}, doc:{state:true}, notice:{state:true}, regex:{state:true}, pattern:{state:true}, loadError:{state:true}};
  page='home'; query=''; status='all'; entries:Capability[]=[]; release:Release|null=null;
  theme='light'; reduced=false; settingsOpen=false; doc='start'; notice=''; regex=false; pattern=''; loadError='';
  private hashHandler=()=>{ const [route,article]=location.hash.replace(/^#\/?/,'').split('/'); this.page=['coverage','docs','releases'].includes(route)?route:'home'; if(article&&docs[article])this.doc=article; };
  createRenderRoot(){return this;}
  connectedCallback(){super.connectedCallback(); try{this.theme=localStorage.getItem('msc.web.theme')||'light';this.reduced=localStorage.getItem('msc.web.motion')==='reduced';}catch{} this.hashHandler();window.addEventListener('hashchange',this.hashHandler);this.applyAppearance();void this.load();}
  disconnectedCallback(){window.removeEventListener('hashchange',this.hashHandler);super.disconnectedCallback();}
  async load(){try{const [c,r]=await Promise.all([fetch('/coverage.json'),fetch('/release.json')]);if(!c.ok||!r.ok)throw new Error('Published metadata is unavailable.');const ledger=await c.json();this.entries=Array.isArray(ledger)?ledger:(ledger.capabilities??ledger.entries??[]);this.release=await r.json();}catch(e){this.loadError=String(e);}}
  applyAppearance(){document.documentElement.dataset.theme=this.theme;document.documentElement.dataset.motion=this.reduced?'reduced':'full';}
  setTheme(v:string){this.theme=v;try{localStorage.setItem('msc.web.theme',v);}catch{}this.applyAppearance();}
  navigate(page:string){location.hash=page==='home'?'#/':`#/${page}`;this.page=page;window.scrollTo({top:0,behavior:this.reduced?'instant':'smooth'});}
  get filtered(){let rx:RegExp|null=null;if(this.regex&&this.pattern){try{rx=new RegExp(this.pattern,'iu');}catch{return[];}}return this.entries.filter(x=>(this.status==='all'||x.status===this.status)&& (rx?rx.test(`${x.referenceCapability} ${x.equivalent} ${x.family}`):`${x.referenceCapability} ${x.equivalent} ${x.family}`.toLowerCase().includes(this.query.toLowerCase())));}
  pill(label:string){return html`<span class="status-label">${label}</span>`;}
  action(label:string,fn:()=>void){return html`<md-filled-button @click=${fn}>${label}</md-filled-button>`;}
  render(){return html`
    <header class="masthead"><div class="brand"><img src="/mark.svg" alt="" width="40" height="40"/><div><strong>Material System Care</strong><span>Windows 11 · x64</span></div></div>
      <nav aria-label="Main navigation">${[['home','Overview'],['coverage','Capabilities'],['docs','Documentation'],['releases','Downloads']].map(([id,label])=>html`<md-text-button class=${this.page===id?'active':''} @click=${()=>this.navigate(id)}>${label}</md-text-button>`)}</nav>
      <md-outlined-button @click=${()=>this.settingsOpen=true}>Appearance</md-outlined-button>
    </header>
    <main id="content" class="page-${this.page}">
      ${this.page==='home'?this.home():this.page==='coverage'?this.coverage():this.page==='docs'?this.documentation():this.downloads()}
      ${this.loadError?html`<section class="notice" role="status">${this.loadError}<md-text-button @click=${()=>{this.loadError='';void this.load();}}>Retry metadata</md-text-button></section>`:nothing}
    </main>
    <footer><div class="brand"><img src="/mark.svg" alt="" width="28" height="28"/><strong>Material System Care</strong></div><p>Independent, open source, and explicit about what is verified.</p><md-text-button href=${source} target="_blank">Source code</md-text-button><md-text-button href=${source+'/issues'} target="_blank">Report a problem</md-text-button><md-text-button @click=${()=>{this.doc='privacy';this.navigate('docs');}}>Privacy</md-text-button><p class="fine">Not affiliated with IObit. Version ${this.release?.version??'unavailable'} · Updated ${this.release?.updatedAt?new Date(this.release.updatedAt).toLocaleString(undefined,{timeZoneName:'short',second:'2-digit',minute:'2-digit',hour:'2-digit',year:'numeric',month:'short',day:'numeric'}):'provenance unavailable'}</p></footer>
    <md-dialog .open=${this.settingsOpen} @closed=${()=>this.settingsOpen=false}><div slot="headline">Make it comfortable</div><form slot="content" id="appearance" method="dialog"><p>Appearance settings stay in this browser.</p><h3>Theme</h3><md-outlined-select label="Theme" .value=${this.theme} @change=${(e:any)=>this.setTheme(e.target.value)}><md-select-option value="light"><div slot="headline">Light</div></md-select-option><md-select-option value="dark"><div slot="headline">Dark</div></md-select-option></md-outlined-select><label class="setting-row"><span><strong>Reduced motion</strong><small>Use immediate state changes. The operating-system preference is always respected.</small></span><md-switch aria-label="Reduced motion" .selected=${this.reduced} @change=${(e:any)=>{this.reduced=e.target.selected;try{localStorage.setItem('msc.web.motion',this.reduced?'reduced':'full');}catch{}this.applyAppearance();}}></md-switch></label><p>Sound is off. This public presentation does not play background audio.</p></form><div slot="actions"><md-text-button @click=${()=>this.settingsOpen=false}>Done</md-text-button></div></md-dialog>
  `;}
  home(){return html`<section class="hero"><div class="hero-copy">${this.pill('Independent · Open source')}<h1>Your PC.<br/><em>Clearly in your control.</em></h1><p class="lead">A considered workspace for computer maintenance. Understand what is happening, choose what changes, and keep the evidence.</p><div class="actions">${this.action('Explore the workspace',()=>this.navigate('coverage'))}<md-outlined-button href=${source} target="_blank">View source</md-outlined-button></div><p class="fine">Windows 11 x64 · Local engine · Explicit recovery records</p></div><div class="hero-graphic" aria-label="The maintenance workflow: inspect, review, act, and recover"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><img src="/mark.svg" alt="Material System Care shield" class="hero-mark"/><div class="flow-label flow-one">01 · Inspect</div><div class="flow-label flow-two">02 · Review</div><div class="flow-label flow-three">03 · Act</div><div class="flow-label flow-four">04 · Recover</div></div></section>
    <section class="principles" aria-labelledby="principles-title"><div class="section-heading"><p class="eyebrow">A calmer way to care</p><h2 id="principles-title">Useful work.<br/>No mystery button.</h2></div><div class="principle-grid">${sections.map(([n,title,body,label])=>html`<article class="material-card"><span class="step-number">${n}</span><h3>${title}</h3><p>${body}</p><span class="category-label">${label}</span></article>`)}</div></section>
    <section class="split-section"><div><p class="eyebrow">One workspace, connected tasks</p><h2>From a finding<br/>to a deliberate action.</h2><p>Storage, applications, startup, protection, drivers, and local utilities share the same approach: real records, contextual controls, and a visible outcome.</p>${this.action('Read the safety model',()=>{this.doc='safety';this.navigate('docs');})}</div><div class="workflow-list">${['Inspect actual records','Select the exact targets','Review effects and recovery','Confirm the chosen operation','Read the final receipt'].map((x,i)=>html`<div class="workflow-step"><span>${String(i+1).padStart(2,'0')}</span><strong>${x}</strong></div>`)}</div></section>
    <section class="coverage-callout"><p class="eyebrow">Evidence over promises</p><h2>A complete catalogue.<br/>An honest status for every capability.</h2><p>Reference coverage and working implementation are separate. Explore the ledger to see what is implemented, what needs verification, and what requires an external adapter.</p><md-filled-tonal-button @click=${()=>this.navigate('coverage')}>Inspect capability coverage</md-filled-tonal-button></section>`;}
  coverage(){const rows=this.filtered;return html`<section class="document-heading"><p class="eyebrow">Capability ledger</p><h1>Know what is actually ready.</h1><p>Each entry retains its reference, intended equivalent, and current implementation state. A catalogue entry is not a completion claim.</p></section><section class="ledger-controls"><md-outlined-text-field label="Search capabilities" .value=${this.query} @input=${(e:any)=>this.query=e.target.value}></md-outlined-text-field><md-outlined-select label="Implementation state" .value=${this.status} @change=${(e:any)=>this.status=e.target.value}>${['all','implemented','unverified','unimplemented','unavailable','excluded'].map(x=>html`<md-select-option value=${x}><div slot="headline">${x==='all'?'All states':x}</div></md-select-option>`)}</md-outlined-select><md-outlined-button @click=${()=>this.regex=!this.regex}>${this.regex?'Close regular expression':'Regular expression'}</md-outlined-button><md-text-button @click=${()=>{this.query='';this.status='all';this.pattern='';this.regex=false;}}>Reset</md-text-button></section>${this.regex?html`<section class="regex-editor"><md-outlined-text-field label="Pattern" supporting-text="Unicode, case-insensitive. Invalid patterns return no matches." .value=${this.pattern} @input=${(e:any)=>this.pattern=e.target.value}></md-outlined-text-field>${['^','$','.*','\\d+','(one|two)'].map(x=>html`<md-outlined-button @click=${()=>this.pattern+=x}>${x}</md-outlined-button>`)}</section>`:nothing}<p role="status">${rows.length} matching entries · ${this.entries.length} total entries</p><section class="ledger-list" aria-label="Capability results">${rows.slice(0,300).map(x=>html`<article class="capability-row"><div>${this.pill(x.status)}<span class="fine">${x.family} · ${x.id}</span><h3>${x.referenceCapability}</h3><p>${x.equivalent}</p></div><p class="status-reason">${x.statusReason}</p></article>`)}</section>${!rows.length?html`<p class="empty-state">No matching capabilities. Adjust the search or state filter.</p>`:nothing}`;}
  documentation(){const d=docs[this.doc];return html`<section class="document-heading"><p class="eyebrow">Documentation</p><h1>Understand the work.</h1><p>Practical guidance, clear limits, and the reasoning behind the controls.</p></section><div class="docs-layout"><nav aria-label="Documentation topics">${Object.entries(docs).map(([id,doc])=>html`<md-text-button class=${id===this.doc?'active':''} @click=${()=>{this.doc=id;location.hash='#/docs/'+id;}}>${doc.title}</md-text-button>`)}</nav><article class="doc-article"><h2>${d.title}</h2>${d.paragraphs.map(p=>html`<p>${p}</p>`)}<md-outlined-button href=${source+'/tree/main/docs'} target="_blank">Read implementation articles</md-outlined-button></article></div>`;}
  downloads(){return html`<section class="document-heading"><p class="eyebrow">Downloads and release history</p><h1>Verified delivery.<br/>Visible provenance.</h1><p>Installer links are taken from the published release manifest. Source availability does not imply that an installer has passed verification.</p></section><section class="download-panel"><div>${this.pill(this.release?.state??'Loading release state')}<h2>Material System Care ${this.release?.version??''}</h2><p>Windows 11 x64. Genuine Squirrel.Windows distribution. Unsigned installers may display an unknown-publisher warning.</p></div><div class="actions">${this.release?.downloadUrl?html`<md-filled-button href=${this.release.downloadUrl}>Download installer</md-filled-button>`:html`<md-filled-button disabled>Installer verification pending</md-filled-button>`}<md-outlined-button href=${this.release?.releaseUrl??source+'/releases'} target="_blank">Release history</md-outlined-button></div></section><section class="build-note"><h2>Build from public source</h2><p>The repository provides root build entrypoints and a pinned dependency manifest. Read the latest build evidence and limitations before treating a development build as a release.</p><code>build.bat --run</code><md-text-button href=${source+'#build'} target="_blank">Build documentation</md-text-button></section>`;}
}
customElements.define('msc-site',MscSite);
